- README.md
- pyproject.toml
- src/chonkie/chunker/late.py
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- src/chonkie/types/late.py
- src/chonkie/types/recursive.py
- src/chonkie/utils.py
- tests/chunkers/test_late_chunker.py
- tests/chunkers/test_recursive_chunker.py
- tests/chunkers/test_semantic_chunker.py
- tests/chunkers/test_sentence_chunker.py
- tests/samples/recipe.json
- tests/test_utils.py
- tests/types/test_recursive.py
Yes, you got that right~ Chonkie loves all languages equally!
> Feat: Add Initial support for `Recipes`  and multilingual CHONKs!

- src/chonkie/embeddings/base.py
- src/chonkie/embeddings/model2vec.py
- src/chonkie/tokenizer.py
- tests/embeddings/test_custom_embeddings.py
- tests/embeddings/test_model2vec_embeddings.py
This pull request includes several changes to the `src/chonkie` and `tests/embeddings` directories, focusing on refactoring and error handling improvements. The most important changes include the removal of token counting methods, the addition of type hints, and the handling of import errors.
Refactoring and code simplification:
* [`src/chonkie/embeddings/base.py`](diffhunk://#diff-849579bb6030628505c4ee859c8913bd4e9d3aa3bc681e1323c23c66b010ad84L66-L93): Removed the `count_tokens` and `count_tokens_batch` methods and updated the `get_tokenizer_or_token_counter` method to raise `NotImplementedError`. [[1]](diffhunk://#diff-849579bb6030628505c4ee859c8913bd4e9d3aa3bc681e1323c23c66b010ad84L66-L93) [[2]](diffhunk://#diff-849579bb6030628505c4ee859c8913bd4e9d3aa3bc681e1323c23c66b010ad84R127) …
> Fix: `WordTokenizer.count_tokens` should use `.tokenize` instead of `.encode`

- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/utils/__init__.py
- src/chonkie/utils/hub.py
- src/chonkie/utils/vizard.py
This pull request introduces new utility functions and visualization capabilities to the `chonkie` package. The key changes include adding a new optional dependency for visualization, updating the `__init__.py` files to include new utility classes, and creating a new `Visualizer` class for visualizing data.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R53-R60): Added `rich` as an optional dependency for visualization.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408R33-R36): Imported `Hubbie` and `Visualizer` from the `utils` module and included them in `__all__`. [[1]](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408R33-R36) …
> Add Chonkie Vizard — easy chunk visualization with `Visualizer`

- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/tokenizer.py
- src/chonkie/types/semantic.py
- src/chonkie/utils/__init__.py
- src/chonkie/utils/hub.py
- src/chonkie/utils/vizard.py
This pull request introduces a new visualization feature and includes several improvements and refactorings to the codebase. The most important changes include adding a new optional dependency for visualization, refactoring utility functions into separate modules, and enhancing the `Visualizer` class for better functionality.
* Added `rich` as an optional dependency for visualization in `pyproject.toml`.
* Moved utility functions into separate modules: `hub.py` and `vizard.py`. Updated imports accordingly in `src/chonkie/__init__.py`. [[1]](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408R33-R36) [[2]](diffhunk://#diff-fa85b88232d1c612eca72da7cd82df62a1bf5a3756ced233a960aa5bb25ef762R1-R6) [[3]](diffhunk://#diff-838625f3fb7fd9962cf73d47c1b0d0fa93ed3ea8285742 …
> Feat: Add Chonkie Vizard to main! `Visualizer` class for easy chunk visualizations

- README.md
- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/chunker/code.py
- src/chonkie/types/__init__.py
- src/chonkie/types/code.py
- src/chonkie/utils/viz.py
- tests/chunkers/test_code_chunker.py
This pull request introduces a new `CodeChunker` class for splitting code into context-aware chunks, along with the necessary supporting types, dependencies, and tests. The changes focus on enabling code chunking functionality and ensuring its integration into the existing system.
* Added the `CodeChunker` class in `src/chonkie/chunker/code.py`, which uses `tree-sitter` and `tree-sitter-language-pack` to split code into chunks based on context. It includes methods for grouping nodes, reconstructing text, and creating chunks.
* Introduced a new `CodeChunk` type in `src/chonkie/types/code.py` to represent individual code chunks, with metadata such as language and associated nodes.
* Updated `pyproject.toml` to include optional dependencies for `tree-sitter` and `tree-sitter-language-pack` …
> Add initial support for chunking code via `CodeChunker`

- README.md
- pyproject.toml
This pull request primarily updates the `README.md` file to improve its structure and readability, and makes a minor adjustment to the `pyproject.toml` file for package organization. The changes focus on enhancing documentation clarity and ensuring proper package inclusion.
* Reorganized sections in the `README.md` for better navigation, adding an inline table of contents with links to sections like "Installation," "Usage," "Chunkers," "Integrations," and "Benchmarks."
* Moved the tagline "_The no-nonsense ultra-light and lightning-fast chunking library..._" to a more prominent position for better visibility.
* Added a new "Integrations" section detailing supported tokenizers and embedding models, making it easier for users to understand Chonkie's compatibility.
* Adjusted formatting in …
> Fix: Attempt fixing `chonkie.cloud` path bug + update README.md to have integrations 

- src/chonkie/__init__.py
- src/chonkie/chunker/__init__.py
> Add Code to init files

- .github/workflows/python-test-push.yml
This pr will update github workflow, allowing it to run on pull requests even before the pr has been merged.
This extra scope will help users create prs that are ruff compatible and do not introduce breaking changes.
> Feat : update test workflow to run on prs even before merging

- pyproject.toml
- src/chonkie/chunker/code.py
This pull request introduces support for automatic language detection in the `CodeChunker` class using the `Magika` library. It also updates dependencies in the `pyproject.toml` file to include `Magika`. Below is a summary of the most important changes:
* Added `magika>=0.6.0, <0.7.0` to the `code` optional dependency and the `all` dependency group in `pyproject.toml`. This enables the use of the Magika library for language detection. [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L54-R54) [[2]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R65)
* Updated the `language` parameter in the `CodeChunker` class to support `Union[Literal["auto"], "SupportedLanguage"]`. This allows users to set `language="auto"` for …
> Feat: Add support for auto-detecting language in `CodeChunker` via `Magika`

- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/chunker/__init__.py
- src/chonkie/chunker/slumber.py
- src/chonkie/genie/__init__.py
- src/chonkie/genie/base.py
- src/chonkie/genie/gemini.py
- src/chonkie/types/recursive.py
This pull request introduces significant updates to the `chonkie` library, including the addition of a new chunker (`SlumberChunker`), integration of a generative inference engine (`Genie`), and enhancements to the `CodeChunker`. These changes expand the library's capabilities for advanced text and code processing while improving modularity and extensibility.
* **SlumberChunker Implementation**: Added a new `SlumberChunker` class that extends `RecursiveChunker` and uses a generative inference engine (`Genie`) to identify semantic shifts in text. This includes a custom prompt template and support for recursive chunking with token-based constraints. (`src/chonkie/chunker/slumber.py`, [src/chonkie/chunker/slumber.pyR1-R137](diffhunk://#diff-dbe17c04b351831fbb70278c629750539e279053e1b2e0dd8d87 …
> Feat: Add initial support for `SlumberChunker`

- .github/workflows/python-test-pr-main.yml
- .github/workflows/python-test-pr.yml
- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- src/chonkie/chunker/slumber.py
- src/chonkie/genie/base.py
- src/chonkie/genie/gemini.py
- tests/chunkers/test_sentence_chunker.py
- tests/embeddings/test_openai_embeddings.py
This pull request introduces significant updates to the `chonkie` library, focusing on refactoring, performance improvements, and enhanced functionality for chunking and tokenization. Key changes include the removal of deprecated methods, updates to chunk creation logic, enhancements to the `SlumberChunker` class, improvements to the `BaseGenie` and `GeminiGenie` classes, and adjustments to the `BaseTokenizer`. These changes aim to streamline the codebase, improve maintainability, and enhance chunking accuracy and performance.
* Removed deprecated methods `_estimate_token_counts` and `_get_feedback` from `sentence.py` to clean up unused and inaccurate functionality.
* Updated `_create_chunk` in `sentence.py` to calculate token counts dynamically, improving accuracy by accounting for …
> Fix: `SlumberChunker`'s splitting algorithm from `RecursiveChunker` to custom + Pickling issue in `BaseTokenizer`

- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/chunker/__init__.py
- src/chonkie/chunker/neural.py
This pull request introduces a new `NeuralChunker` class for text chunking using a neural approach, along with updates to integrate it into the codebase. Key changes include the addition of the `NeuralChunker` implementation, updates to imports and exports, and a new dependency on the `transformers` library.
* Added the `NeuralChunker` class in `src/chonkie/chunker/neural.py`. This class uses a token classification model to predict text split points and includes methods for dependency management, merging spans, and generating chunks.
* Updated `src/chonkie/chunker/__init__.py` to import and export `NeuralChunker` for use in the chunking module. [[1]](diffhunk://#diff-b9f7a0e97cb51825efbeeb27c7cfa1aafcaba2213c98ff81d052b1fc909940a1R6) …
> Feat: Add initial support for the `NeuralChunker`

- src/chonkie/chunker/slumber.py
- src/chonkie/utils/viz.py
This pull request introduces a new prompt template with context support in the `SlumberChunker` and adds a new "tiktokenizer" theme to the visualization utilities. These changes enhance functionality for text chunking and provide additional customization for visualizations.
* Added a new prompt template, `PROMPT_W_CONTEXT_TEMPLATE`, in `src/chonkie/chunker/slumber.py`. This template allows for the inclusion of user-provided context to improve the identification of content shifts in passages.
* Introduced a new theme, `TIKTOKENIZER_THEME`, in `src/chonkie/utils/viz.py`, which includes a set of pastel colors for visualization purposes.
* Updated the `_get_theme` method in `src/chonkie/utils/viz.py` to support the new "tiktokenizer" theme, enabling its selection during runtime.
> Feat: Add `tiktokenizer` theme to the `Visualizer`

- DOCS.md
- src/chonkie/chunker/neural.py
This pull request includes a minor update to the `__repr__` method of the `NeuralChunker` class in `src/chonkie/chunker/neural.py`. The change adds the `tokenizer` attribute to the string representation of the object for improved debugging and clarity.
> Add the local DOCS.md for consistency and ease

- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/friends/__init__.py
- src/chonkie/friends/handshakes/__init__.py
- src/chonkie/friends/handshakes/turbopuffer.py
- src/chonkie/genie/__init__.py
- src/chonkie/genie/gemini.py
- src/chonkie/genie/openai.py
This pull request introduces a new `OpenAIGenie` class to the `chonkie` package, enhancing its functionality with support for OpenAI's API. Additionally, it includes minor improvements to the existing `GeminiGenie` class and updates to the module exports to reflect these changes.
* Added the `OpenAIGenie` class in `src/chonkie/genie/openai.py` to integrate with OpenAI's API, including methods for generating text and JSON responses, dependency checks, and lazy imports. (`[src/chonkie/genie/openai.pyR1-R99](diffhunk://#diff-3d71428c5a8ea0f0559929659dd14470c62d759b1f866eea9144b8af0b4dac8bR1-R99)`)
* Updated `__init__.py` files in `src/chonkie` and `src/chonkie/genie` to include `OpenAIGenie` in the module exports. (`[[1]](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309a …
> Feat: Add support for `OpenAIGenie` + `TurbopufferHandshake`

- src/chonkie/embeddings/openai.py
This pull request introduces enhancements and refactoring to the `OpenAIEmbeddings` class in `src/chonkie/embeddings/openai.py`. The changes improve flexibility by adding new parameters, updating the constructor logic, and enhancing the class docstring for better clarity.
* **Added new parameters for flexibility**:
- Introduced `tokenizer`, `dimension`, `base_url`, and `**kwargs` as optional parameters to the `__init__` method. These additions allow greater customization when initializing the class. (`[src/chonkie/embeddings/openai.pyR47-R103](diffhunk://#diff-1c6fe14879ec1f5807d2d569f4c80592b608d1fa67722bce3516116f617c8645R47-R103)`)
* **Updated constructor logic**:
- Added conditional logic to handle the `tokenizer` and `dimension` parameters. The logic ensures these values are either …
> Feat: Add the `base_url` to the `OpenAIEmbeddings` and `**kwargs` support

- src/chonkie/cloud/__init__.py
- src/chonkie/cloud/chunker/__init__.py
- src/chonkie/cloud/chunker/neural.py
- src/chonkie/cloud/chunker/recursive.py
- src/chonkie/cloud/chunker/semantic.py
- src/chonkie/cloud/chunker/sentence.py
- src/chonkie/cloud/chunker/slumber.py
- src/chonkie/cloud/chunker/token.py
- tests/cloud/test_cloud_late_chunker.py
- tests/cloud/test_cloud_neural_chunker.py
- tests/cloud/test_cloud_sdpm_chunker.py
- tests/cloud/test_cloud_slumber_chunker.py
This pull request introduces two new chunking classes, `NeuralChunker` and `SlumberChunker`, to the Chonkie API, along with their integration into the module's imports and exports. These additions enhance the functionality of the library by providing advanced chunking strategies. Below is a summary of the changes:
* **`NeuralChunker`**:
- Implements a neural-based chunking strategy using a configurable model and API integration. 
- Includes validation for API keys, supported models, and response handling from the Chonkie API.
* **`SlumberChunker`**:
- Implements a chunking strategy based on recursive rules and tokenization, with robust error handling for API interactions.
- Supports additional configuration options such as `chunk_size`, `candidate_size`, and `rules`.
* Updated …
> Enhance chunker module by adding NeuralChunker and SlumberChunker to the imports and __all__ list for improved functionality.

- src/chonkie/cloud/chunker/neural.py
This pull request updates error messages in the `src/chonkie/cloud/chunker/neural.py` file to provide more user-friendly and actionable feedback when exceptions occur.
* Updated the error message in the `__init__` method to a more conversational tone, informing users that the Chonkie API is temporarily down and advising them to try again later or contact support if the issue persists.
* Updated the error message in the `chunk` method to clarify that the Chonkie API returned an invalid response, suggesting users check their input and contact support if the problem continues.
> Minor: fix error messages in `cloud.NeuralChunker`

- pyproject.toml
- src/chonkie/__init__.py
- tests/refinery/__init__.py
- tests/refinery/test_overlap_refinery.py
This PR adds comprehensive tests for the `OverlapRefinery` class to improve test coverage.
- Created a new test directory structure for refinery tests
- Added 19 test cases for the `OverlapRefinery` class
- Increased test coverage for `overlap.py` from 16% to 64%
- Increased overall repository test coverage from 30% to 33%
All tests are passing. The test coverage for the `OverlapRefinery` module has been significantly improved.
```
Name                              Stmts   Miss  Cover
-----------------------------------------------------
src/chonkie/refinery/overlap.py     140     50    64%
-----------------------------------------------------
TOTAL                               140     50    64%
```
Further improvements could be made by:
- Adding tests for the recursive overlap methods
- …
> Improve test coverage for OverlapRefinery

- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/embeddings/base.py
- src/chonkie/embeddings/cohere.py
- src/chonkie/embeddings/model2vec.py
- src/chonkie/embeddings/openai.py
- src/chonkie/embeddings/sentence_transformer.py
- src/chonkie/embeddings/voyageai.py
- src/chonkie/refinery/base.py
- src/chonkie/refinery/embedding.py
- src/chonkie/refinery/overlap.py
- tests/chunkers/test_slumber_chunker.py
- tests/embeddings/test_cohere_embeddings.py
- tests/embeddings/test_model2vec_embeddings.py
- tests/embeddings/test_openai_embeddings.py
- tests/embeddings/test_sentence_transformer_embeddings.py
- tests/embeddings/test_voyageai_embeddings.py
- tests/genie/test_base_genie.py
- tests/genie/test_gemini_genie.py
- tests/genie/test_openai_genie.py
- tests/refinery/test_overlap_refinery.py
- tests/test_tokenizer.py
This pull request introduces a comprehensive suite of unit tests for the `OverlapRefinery` class in the `chonkie.refinery` module. These tests cover initialization, validation of parameters, and behavior under various configurations. The changes include the addition of a new test file and a fixture for reusable sample data.
* **Initialization Tests**:
- Added tests to validate default initialization and ensure proper handling of invalid parameters such as `context_size`, `mode`, `method`, `merge`, and `inplace`.
* **Behavioral Tests**:
- Added tests for the `refine` method to verify behavior with empty chunks, different chunk types, and various configurations (e.g., `inplace=False`, `merge=False`).
* **Context Overlap Tests**:
- Added tests for token-based overlap with both prefix and …
> Feat: Enhance the tests for `OverlapRefinery`, `Tokenizers` and `SlumberChunker`

- src/chonkie/cloud/__init__.py
- src/chonkie/cloud/chunker/__init__.py
- src/chonkie/cloud/chunker/code.py
- tests/cloud/test_cloud_code_chunker.py
- tests/embeddings/test_auto_embeddings.py
- tests/embeddings/test_embeddings_registry.py
- tests/embeddings/test_jina_embeddings.py
- tests/embeddings/test_voyageai_embeddings.py
- tests/porters/test_json_porter.py
This pull request introduces the `CodeChunker` class to the Chonkie Cloud API for chunking code, along with corresponding updates to the module's initialization files and a comprehensive set of tests. The most important changes include the implementation of the `CodeChunker` class, updates to module imports and exports, and the addition of extensive unit tests to ensure functionality.
* Added the `CodeChunker` class in `src/chonkie/cloud/chunker/code.py`, which provides functionality for chunking code using the Chonkie API. It supports configurable chunk sizes, tokenizers, languages, and return types. The class validates input parameters, handles API requests, and processes responses.
* Updated `src/chonkie/cloud/__init__.py` and `src/chonkie/cloud/chunker/__init__.py` to include the …
> Feat: Add cloud `CodeChunker` + tests

- cookbook/examples/gemini_embeddings_with_recursive_chunking.py
- cookbook/examples/psycopg_handshake_with_recursive_chunking.py
- cookbook/examples/recursive_chunker_json_export.py
- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/embeddings/jina.py
- src/chonkie/embeddings/model2vec.py
- src/chonkie/embeddings/openai.py
- src/chonkie/embeddings/voyageai.py
- src/chonkie/friends/__init__.py
- src/chonkie/friends/handshakes/__init__.py
- src/chonkie/friends/handshakes/chroma.py
- src/chonkie/friends/handshakes/psycopg.py
- src/chonkie/friends/handshakes/turbopuffer.py
- src/chonkie/refinery/overlap.py
- tests/chunkers/test_sentence_chunker.py
- tests/chunkers/test_token_chunker.py
- tests/handshakes/test_chroma_handshake.py
- tests/handshakes/test_psycopg_handshake.py
- tests/handshakes/test_qdrant_handshake.py
- tests/refinery/test_embedding_refinery.py
- tests/refinery/test_overlap_refinery.py
This pull request introduces several updates, including the addition of a new example for PostgreSQL integration with pgvector, improvements to existing examples, and various codebase enhancements. The most significant changes include adding the `PsycopgHandshake` feature, updating dependencies, and improving code readability.
* Added a new example file `cookbook/examples/psycopg_handshake_with_recursive_chunking.py` demonstrating how to use `PsycopgHandshake` with PostgreSQL and pgvector for semantic similarity search. This includes connection setup, chunk storage, vector indexing, and search capabilities.
* Introduced `PsycopgHandshake` to the `src/chonkie` package, updating imports and exports in `__init__.py` files across multiple modules to include this new feature. …
> Feat: Add support for `PsycopgHandshake`

- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/chef/__init__.py
- src/chonkie/chef/base.py
- src/chonkie/chef/text.py
- src/chonkie/fetcher/__init__.py
- src/chonkie/fetcher/base.py
- src/chonkie/fetcher/file.py
- tests/chef/__init__.py
- tests/chef/test_chef.py
- tests/fetcher/__init__.py
- tests/fetcher/test_fetcher.py
This pull request introduces two new modules, `chef` and `fetcher`, to extend the functionality of the `chonkie` package. The `chef` module provides tools for processing text data, while the `fetcher` module handles fetching files from directories. Additionally, comprehensive tests have been added for both modules to ensure reliability and correctness.
* [`src/chonkie/chef/__init__.py`](diffhunk://#diff-bbcfb56203004de2788bbf1e42e2e959e1e2f3788a9f9f5476d5178f04ed410aR1-R6): Introduced the `chef` module with `BaseChef` and `TextChef` classes.
* [`src/chonkie/chef/base.py`](diffhunk://#diff-4f3da52cf64abd0d188ef4f93f481bdf52aeec37f7ad113f5f4e1104d443066eR1-R20): Added `BaseChef`, an abstract base class for chefs with a `process` method that subclasses must implement.
* …
> Feat: Add support for `FileFetcher` and `TextChef` classes — for better input support in `chonkie`

- src/chonkie/embeddings/jina.py
- src/chonkie/embeddings/registry.py
- tests/embeddings/test_jina_embeddings.py
- Updated available jina embedding models with latest jina-embeddings-v4
- Updated the test cases.
- Made jina-embeddings-v4 default model
- Verified all the test cases (Passed)
> Feat: Added jina embedding v4 model

- docs/python-sdk/handshakes/mongodb-handshake.mdx
> Docs: update mongodb docs

- README.md
> Docs: update readme to include the latest handshakes

- src/chonkie/handshakes/pinecone.py
- tests/porters/test_datasets_porter.py
This pr is part of the pinecone integration that i mentioned internally + I formatted the file using ruff
> Feat: add pinecone source_tag 

- src/chonkie/__init__.py
- src/chonkie/chunker/__init__.py
- src/chonkie/chunker/table.py
- src/chonkie/chunker/token.py
**TODO:**
```python
from chonkie import TableChunker
chunker = TableChunker("gpt2",chunk_size=200)
table = """
| Name    | Age | City         | comments          |
|---------|-----|--------------|--------------------|
| Alice   | 25  | New York     | Loves hiking and outdoor activities. |
| Bob     | 30  | San Francisco| Enjoys tech meetups and coding.      |
| Charlie | 35  | Los Angeles  | Avid reader and coffee enthusiast.    |
| Diana   | 28  | Chicago      | Passionate about art and music.       |
| Ethan   | 32  | Miami        | Fitness lover and foodie.             |
| Fiona   | 27  | Seattle      | Tech enthusiast and gamer.            |
| George  | 29  | Boston       | History buff and museum goer.
| Hannah  | 31  | Austin       | Musician and festival fan.            |
| Ian …
```
> Feat: add table chunker

- docs/docs.json
- docs/python-sdk/handshakes/elastic-handshake.mdx
- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/handshakes/__init__.py
- src/chonkie/handshakes/elastic.py
- tests/handshakes/test_elastic_handshake.py
This PR introduces the `ElasticHandshake`, adding support for Elasticsearch as a vector store for Chonkie. 
*   **`ElasticHandshake` Implementation:** Created the core `ElasticHandshake` class in `src/chonkie/handshakes/elastic.py`. It handles:
*   Connection to local or Elastic Cloud instances.
*   Automatic index creation with the correct `dense_vector` mapping.
*   Efficient batch ingestion using the `elasticsearch.helpers.bulk` API.
*   A `search` method that performs kNN vector search.
*   **Unit Tests:** Added `tests/handshakes/test_elastic_handshake.py`.
*   **Documentation:**  `docs/python-sdk/handshakes/elastic-handshake.mdx`
*   **Project Integration:**
*   Exposed the new class in `src/chonkie/handshakes/__init__.py`.
*   Added the optional dependency `elasticsearch` to …
> Feat: Add ElasticHandshake

- docs/chonkie-cloud/openapi.json
- src/chonkie/cloud/chunker/neural.py
- Update chonkie cloud docs to match the new param options. 
- Update cloud neural chunker to no longer accept stride.
> Docs: Update Cloud API docs
