chonkie-inc/chonkie

pyproject.toml
This pull request includes a small change to the `pyproject.toml` file. The change adds the `chonkie.utils` package to the list of packages.
=> Fix: Add `chonkie.utils` module to package list in `pyproject.toml`

pyproject.toml, src/chonkie/__init__.py, src/chonkie/cloud/__init__.py, src/chonkie/cloud/chunkers/__init__.py
This pull request includes version updates and import path simplifications for the `chonkie` project. The most important changes are summarized below:
Version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the project version from `1.0.3a1` to `1.0.3`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L39-R39): Updated the `__version__` attribute from `1.0.3a1` to `1.0.3`.
Import path simplifications:
* [`src/chonkie/cloud/__init__.py`](diffhunk://#diff-d755310e35499ddbbf52812fca4020d8ee4f16ca454281516ec8769890295369L3-R3): Changed import paths to use relative imports for chunker modules.
* [`src/chonkie/cloud/chunkers/__init__.py`](diffhunk://#diff-d …
=> Fix: `chonkie.cloud` does not contain `chunkers` error + bump up version to `v1.0.3`

README.md, pyproject.toml, src/chonkie/__init__.py, src/chonkie/chunker/__init__.py, tests/chunkers/test_code_chunker.py
This pull request introduces a new `CodeChunker` class to the `chonkie` library and updates the version to `1.0.5`. The changes primarily focus on adding the new chunker and ensuring it is properly integrated into the module's exports.
* Updated the version from `1.0.4` to `1.0.5` in `pyproject.toml` and `src/chonkie/__init__.py`. [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7) [[2]](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L46-R47)
* Added `CodeChunker` to the import statements in `src/chonkie/__init__.py` and `src/chonkie/chunker/__init__.py`. [[1]](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408R5) [[2]](diffhunk://#diff-b9f7a0e97cb51825efbeeb27c7cfa1aafcaba2213c98ff81 …
=> Fix: Export `CodeChunker` properly to the main `chonkie.__init__` + Bump up version to `v1.0.5`

cookbook/tutorials/Chonkie_SlumberChunker_w_OpenRouter_models.ipynb
This pull request updates the tutorial notebook `Chonkie_SlumberChunker_w_OpenRouter_models.ipynb` to improve readability and streamline the setup process. The changes include consolidating initialization steps, adding a new markdown explanation, and renaming a section header for clarity.
* Consolidated initialization steps for components like `Console`, `Visualizer`, and `OpenAIGenie` into a single code cell to improve readability and reduce redundancy.
* Added a new markdown cell to confirm that the setup is complete and ready for use with SlumberChunker and OpenRouter.
* Renamed a markdown section header from "Case 1: Article-esque Text with clear sectional demarcations!" to "Now, let's CHONK some documents!" for a more engaging and user-friendly tone.
=> Tutorial: Update the readability of the tutorial with better markdown 

pyproject.toml, src/chonkie/cloud/__init__.py, src/chonkie/cloud/chunker/__init__.py, src/chonkie/cloud/chunker/late.py, src/chonkie/cloud/chunker/sdpm.py, src/chonkie/cloud/chunker/semantic.py, src/chonkie/friends/handshakes/turbopuffer.py, src/chonkie/types/document.py, tests/handshakes/test_chroma_handshake.py, tests/handshakes/test_qdrant_handshake.py
This pull request introduces new chunking strategies, enhances optional dependencies, and improves code organization and documentation. The most significant changes include adding two new chunkers (`LateChunker` and `SDPMChunker`), restructuring optional dependencies in `pyproject.toml`, and refining documentation for better clarity.
* Added `LateChunker` class for late chunking via the Chonkie API, including methods for chunking text and creating instances from recipes (`src/chonkie/cloud/chunker/late.py`).
* Added `SDPMChunker` class for Semantic Double-Pass Merging, implementing advanced chunking logic with various configurable parameters (`src/chonkie/cloud/chunker/sdpm.py`).
* Restructured optional dependencies in `pyproject.toml` to group them by functionality (e.g., chunkers, …
=> Fix: Linting errors + Add `cloud.SDPMChunker` + `cloud.LateChunker` 

cookbook/README.md
This pull request updates the `cookbook/README.md` file to include a new resource in the list of projects. The addition highlights a repository related to the Retrieval-Augmented Generation (RAG) ecosystem.
Content addition:
* Added a new project, `RAGHub`, to the cookbook. This project is described as a living collection of frameworks, projects, and resources in the RAG ecosystem.
=> Add `RAGHub`

src/chonkie/embeddings/auto.py, src/chonkie/embeddings/model2vec.py, src/chonkie/embeddings/registry.py
This pull request refactors the embedding registry and improves the `get_embeddings` method to enhance modularity, error handling, and support for provider aliases. Key changes include restructuring the registry to separate models, providers, patterns, and types, updating the `get_embeddings` logic to handle provider aliases, and simplifying error messages. Additionally, minor updates were made to improve code readability and maintainability.
* Added support for provider aliases (e.g., `provider://model`) in the `get_embeddings` method, enabling more flexible model selection. Improved error handling with detailed messages for missing providers or failed instantiation. (`src/chonkie/embeddings/auto.py`, [src/chonkie/embeddings/auto.pyR65-L99](diffhunk://#diff-0e95a5656987bd1c00cac6f2cf53671 …
=> Feat: Add `URI` support via `provider://organization/model` style strings in `AutoEmbeddings`

src/chonkie/tokenizer.py
Fixes #56
This PR fixes the pickling issue in BaseTokenizer by using a named method instead of a lambda function for the defaultdict factory. Lambda functions cannot be pickled when they capture local variables, which was causing the error `Can't pickle local object 'BaseTokenizer.__init__.<locals>.<lambda>'` when trying to run batching via RecursiveChunker.
=> Fix pickling issue in BaseTokenizer

src/chonkie/refinery/overlap.py, tests/cloud/test_cloud_code_chunker.py, tests/refinery/test_overlap_refinery.py
This pull request introduces performance optimizations and type annotations to the `overlap.py` file in the `chonkie` module and updates the corresponding test suite to improve clarity and correctness. The key changes include adding caching mechanisms for repeated operations, refining token count calculations, and ensuring type annotations for better code readability and maintainability.
* Added caching for tokenization and token count operations to reduce redundant computations and improve performance (`_token_cache` and `_count_cache`). [[1]](diffhunk://#diff-80725268365cb5d6bae898943f18604b84bce3021014d1406a3db4d9bfa4723bR73-R77) [[2]](diffhunk://#diff-80725268365cb5d6bae898943f18604b84bce3021014d1406a3db4d9bfa4723bR176-R182) [[3]](diffhunk://#diff-80725268365cb5d6bae898943f18604b84bce3 …
=> Fix: OverlapRefinery with `mode="recursive"` fails with level gets too low

src/chonkie/refinery/overlap.py, tests/refinery/test_embedding_refinery.py, tests/refinery/test_overlap_refinery.py
This pull request addresses a bug in the `OverlapRefinery` class where a cached context size caused incorrect behavior when reusing the class with different chunk sets. The changes remove the caching mechanism for the calculated context size and add a new test to ensure correctness.
* Removed the `_calculated_context_size` cache from the `OverlapRefinery` class to ensure that the context size is recalculated for each set of chunks when `context_size` is a float. (`src/chonkie/refinery/overlap.py`, [[1]](diffhunk://#diff-80725268365cb5d6bae898943f18604b84bce3021014d1406a3db4d9bfa4723bL76) [[2]](diffhunk://#diff-80725268365cb5d6bae898943f18604b84bce3021014d1406a3db4d9bfa4723bL391-R392)
* Added a new test, `test_overlap_refinery_context_size_reuse_correctness`, to validate that the …
=> Fix: `OverlapRefinery` is caching too much; revert `context_size` calculation caching

pyproject.toml, src/chonkie/__init__.py
This pull request includes a version bump for the `chonkie` library from `1.0.8` to `1.0.9`. The changes update the version in both the `pyproject.toml` file and the `src/chonkie/__init__.py` file.
Version update:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the `version` field under `[project]` to `1.0.9`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L69-R69): Updated the `__version__` variable to `1.0.9`.
=> Update version to 1.0.9 in pyproject.toml for the next release.

.github/workflows/python-publish-wheels.yml, pyproject.toml
This pull request updates the Python wheel publishing workflow to streamline the build process by integrating the `uv` tool and adjusting the platform matrix. Additionally, it removes outdated `cibuildwheel` configurations from `pyproject.toml`. Below are the key changes:
* Limited the operating system matrix in `.github/workflows/python-publish-wheels.yml` to `ubuntu-latest` and `macos-13` for initial testing, removing `windows-latest` and `macos-latest`.
* Replaced `pypa/cibuildwheel` with the `uv` tool for building wheels and source distributions, including new steps to install and set up `uv`. [[1]](diffhunk://#diff-2849a829827cd04b191e7fd46d1fa37c72f70a42743ab7f3f9ea4c5508a1582cL19-R44) [[2]](diffhunk://#diff-2849a829827cd04b191e7fd46d1fa37c72f70a42743ab7f3f9ea4c5508a1582cR53-R60)
* …
=> Fix: Update the CD script to use `uv` instead in the hopes of finally publishing the `v1.0.9` 

pyproject.toml, src/chonkie/__init__.py
This pull request updates the version of the `chonkie` library from `1.0.9` to `1.0.10`. The changes ensure consistency across the project files.
Version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the `version` field from `1.0.9` to `1.0.10`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L72-R72): Updated the `__version__` attribute from `1.0.9` to `1.0.10`.
=> Bump up the version to `v1.0.10`

cookbook/examples/pgvector_handshake_with_recursive_chunking.py, src/chonkie/chunker/base.py, src/chonkie/chunker/code.py, src/chonkie/chunker/late.py, src/chonkie/chunker/neural.py, src/chonkie/chunker/recursive.py, src/chonkie/chunker/sdpm.py, src/chonkie/chunker/semantic.py, src/chonkie/chunker/sentence.py, src/chonkie/chunker/slumber.py, src/chonkie/chunker/token.py, src/chonkie/cloud/chunker/token.py, tests/chunkers/test_code_chunker.py, tests/chunkers/test_neural_chunker.py, tests/chunkers/test_recursive_chunker.py, tests/chunkers/test_sdpm_chunker.py, tests/chunkers/test_semantic_chunker.py, tests/chunkers/test_sentence_chunker.py, tests/chunkers/test_slumber_chunker.py, tests/chunkers/test_token_chunker.py
This pull request simplifies the `Chunker` classes across multiple files by removing the `return_type` parameter and standardizing the return type for chunking methods to always return chunks instead of optionally returning texts. Additionally, it cleans up type annotations and removes redundant code related to the `return_type`.
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L35-R35): Updated methods like `__call__`, `_sequential_batch_processing`, `_parallel_batch_processing`, and `chunk` to always return `Sequence[Chunk]` instead of supporting both chunks and texts. Removed unnecessary `type: ignore` comments for return values. [[1]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L35-R3 …
=> Fix: return_type is removed for returning only `chunks` to simplify mypy static typing

.github/workflows/python-publish-wheels.yml, pyproject.toml, src/chonkie/__init__.py
This pull request includes updates to the CI workflow, versioning, and dependency formatting for the `chonkie` project. The most notable changes include adding Windows support to the build matrix, introducing a pre-release version, and improving the readability of dependency lists.
* [`.github/workflows/python-publish-wheels.yml`](diffhunk://#diff-2849a829827cd04b191e7fd46d1fa37c72f70a42743ab7f3f9ea4c5508a1582cL19-R20): Added Windows (`windows-latest`) to the build matrix for generating wheels, alongside Linux and macOS. This expands platform support.
* [`.github/workflows/python-publish-wheels.yml`](diffhunk://#diff-2849a829827cd04b191e7fd46d1fa37c72f70a42743ab7f3f9ea4c5508a1582cR41-R42): Introduced `CIBW_ENVIRONMENT_WINDOWS` to set `PIP_PREFER_BINARY=1`, ensuring proper handling of …
=> Feat: Bump version and add pre-built wheels for windows to avoid #212

src/chonkie/embeddings/__init__.py
While following the official documentation tutorial for creating [custom embedding handlers](https://docs.chonkie.ai/python-sdk/embeddings/custom-embeddings), I encountered an ImportError when trying to import EmbeddingsRegistry:
```bash
Traceback (most recent call last):
File "/root/embedding/xxx.py", line 11, in <module>
from chonkie.embeddings import BaseEmbeddings, EmbeddingsRegistry, AutoEmbeddings
ImportError: cannot import name 'EmbeddingsRegistry' from 'chonkie.embeddings'
(/root/embedding/.venv/lib/python3.12/site-packages/chonkie/embeddings/__init__.py)
```
The documentation at [docs/python-sdk/embeddings/custom-embeddings.mdx](https://github.com/chonkie-inc/chonkie/blob/8bb30ee3f661a332cf52c561f021295452d0c8c8/docs/python-sdk/embeddings/custom-embeddings.mdx?plain=1#L54) shows: …
=> fix: export EmbeddingsRegistry in embeddings module

README.md
This pull request updates the `README.md` to reflect new features, integrations, and improvements in Chonkie. The documentation now showcases expanded support for more integrations, clarifies optional installation dependencies, and introduces new components such as refineries, utilities, and data preprocessing helpers.
**Integration and Feature Expansion:**
* Increased the number of supported integrations from 19+ to 24+, now including refineries and utilities in addition to tokenizers, embedding providers, LLMs, porters, and vector databases.
* Added new refineries (`OverlapRefinery`, `EmbeddingsRefinery`) for post-processing and enhancing chunks after initial chunking.
* Expanded embedding providers to 8+, now including `AzureOpenAIEmbeddings`.
* Added a new LLM provider …
=> Update README.md — Add recent integrations to the list

docs/python-sdk/getting-started/introduction.mdx
This pull request makes a minor update to the documentation for the Python SDK, clarifying the link to the Installation page.
* Updated the reference in the installation note to point to the correct Installation documentation at `/python-sdk/getting-started/installation` instead of `/installation`.
=> docs: fix url

.github/workflows/python-test-pr-main.yml, .github/workflows/python-test-pr.yml, pyproject.toml, src/chonkie/friends/handshakes/weaviate.py, tests/handshakes/test_weaviate_handshake.py, uv.lock
This pull request makes a minor change to the Weaviate handshake tests by skipping the cloud initialization test. The test was previously attempting to mock cloud connectivity, but is now skipped due to the complexity of mocking lazy-imported modules and the need for real credentials.
* Testing improvements:
* [`tests/handshakes/test_weaviate_handshake.py`](diffhunk://#diff-8246605585528663753046f22eacdababf2e0b78aa1275499637228366c3cf1eR175-R182): Marked `test_weaviate_handshake_cloud_init` as skipped, with a note explaining that cloud connection requires complex mocking due to lazy import, and that the functionality is covered by other tests.
=> Fix: Remove failing weaviate cloud tests from CI/CD

src/chonkie/chef/markdown.py, src/chonkie/types/markdown.py
This pull request enhances the Markdown image extraction logic and improves chunk extraction robustness in the `src/chonkie/chef/markdown.py` module. The main improvements are support for images that are also links, capturing associated link URLs, and ensuring that only meaningful content is chunked. Additionally, the `MarkdownImage` data class is updated to store link information.
**Markdown image extraction improvements:**
* Updated the image regex in `__init__` to support Markdown images that are also links, allowing extraction of both standalone images and images wrapped in links.
* Modified `extract_images` to extract the image's alt text, source, and (if present) the link URL, and to pass the link URL to the `MarkdownImage` object. …
=> Feat: Add support for wrapped `MarkdownImages` and filter empty text blocks in MarkdownChef

src/chonkie/chef/markdown.py, tests/chef/test_base_chef.py, tests/chef/test_chef.py, tests/chef/test_markdown_chef.py, tests/chef/test_table_chef.py
This pull request restructures and improves the test suite for the `chef` module, focusing on better organization and clarity. The tests for `BaseChef` and `TableChef` have been separated into their own files, redundant code has been removed, and some minor improvements have been made to test coverage and correctness. Additionally, the `MarkdownChef` class is refactored to improve the separation of parsing and file reading logic.
**Test Suite Refactoring and Organization:**
* Moved all `TableChef`-related tests from `tests/chef/test_chef.py` into a new dedicated file `tests/chef/test_table_chef.py`, improving test organization and maintainability. [[1]](diffhunk://#diff-c6bf8175ea489e5aedf92af6fa6ac5ae50d5ee463ac472436bcde2ce51c16618L1-L206) …
=> Feat: Add `parse` method to the `MarkdownChef` + Enhance testing for chefs
